### PR TITLE
Switch to pc for compiling.

### PR DESCRIPTION
**Pull request by djnym**
Also updated rebar3 to most recent version.  @mazenharake if you merge can you also tag 0.5.2 with this version.  Thanks!

### CODE REVIEW

**Comment by djnym** [comment]
@mazenharake, it's been awhile and I haven't heard back about this one.  I added a second minor change which allows this to compile without error under erlang 20.  Hopefully, this can be merged and tagged at some point.

**Comment by mazenharake** [comment]
Hi again,

I'm super busy with work and kids.

Want to take over the project?

/M

**Comment by mazenharake** [comment]
Done!  Have fun ;)

**Comment by mazenharake** [comment]
Just FYI, you can't change the copyright or the License file.

Technically the copyright of the contributions you do are yours but since
you send a pull request you implicitly give the copyright to me.

If you can just reply to this email saying that copyright stays with me it
should be fine.

The copyright only protects the license type of the project and since the
license is open it will never stop anyone from getting the copy of the
software even if I, for whatever reason, would change the license you could
always fork a copy from a version where the license was MIT, so this is
just formality. I want to keep it this project open and free.

BR
/M

**Comment by djnym** [comment]
I have no issues with leaving Copyright with you.

I'm not sure if you also want to add me as a collaborator on entop as I'll have some followup
PR's there.

**Comment by mazenharake** [comment]
Sure no problem,
I added you to entop as well!

**Pull request merged**
